module_name: Product tooltips
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - product page
  - statistics
description_short: Shows information on a product page: how many people are viewing it, the last time it was sold and the last time it was added to a cart.
description: description.md
images:
  - image-1.png
license: AFL 3.0
